# Site settings
title: BPS Translation Agency
email: bpstranslation@gmail.com
description: "Your reliable fixer"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503 
  secondary-dark: 000

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/pub/bpstranslation
  - title: github
    url: http://github.com/y7kim
  - title: envelope
    url: mailto:bpstranslation@gmail.com

# Postal address (add as many lines as necessary)
address:
  - line: 408, Say Da Nar (2) St., 43 Qtr
  - line: North Dagon Tsp, Yangon

# Build settings
markdown: kramdown
permalink: pretty
